apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: trading-bot-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      initContainers:
      - name: reset-session-lock
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          kubectl patch configmap websocket-session-lock -n trading-bot-ingestion --type=merge -p '{"data":{"session_status":"unlocked"}}'
        env:
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc.cluster.local"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
      containers:
      - name: kafka-producer
        image: mhupp/kafka-producer:latest
        env:
        - name: BROKER_API_KEY
          valueFrom:
            secretKeyRef:
              name: broker-data-api-secret
              key: BROKER_API_KEY
        - name: BROKER_API_URL
          valueFrom:
            secretKeyRef:
              name: broker-data-api-secret
              key: BROKER_API_URL
        - name: BROKER_API_SECRET
          valueFrom:
            secretKeyRef:
              name: broker-data-api-secret
              key: BROKER_API_SECRET
        - name: KAFKA_BOOTSTRAP_SERVER
          value: "kafka-service.trading-bot-ingestion.svc.cluster.local:9092"
        ports:
        - containerPort: 9092
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
