# role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-access-binding
  namespace: trading-bot-ingestion
subjects:
- kind: ServiceAccount
  name: default
  namespace: trading-bot-ingestion
roleRef:
  kind: Role
  name: configmap-reader-writer
  apiGroup: rbac.authorization.k8s.io
