apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/mhupp/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Sun, 15 Dec 2024 13:48:30 CET
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://127.0.0.1:52167
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Sun, 15 Dec 2024 13:48:30 CET
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/mhupp/.minikube/profiles/minikube/client.crt
    client-key: /home/mhupp/.minikube/profiles/minikube/client.key
