"""added predicitons model

Revision ID: 2287d8d69e9f
Revises: 0a7e20ea06dc
Create Date: 2024-12-16 19:43:21.223224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2287d8d69e9f'
down_revision: Union[str, None] = '0a7e20ea06dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_data_prediction', sa.Column('prediction', sa.DECIMAL(), nullable=True))
    op.drop_column('stock_data_prediction', 'predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_data_prediction', sa.Column('predictions', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('stock_data_prediction', 'prediction')
    # ### end Alembic commands ###
