"""added std 200 and target column

Revision ID: 6910163a9cb6
Revises: 4cd911e0e695
Create Date: 2024-12-15 17:32:11.189747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6910163a9cb6'
down_revision: Union[str, None] = '4cd911e0e695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_data_processed', sa.Column('rolling_std_200', sa.DECIMAL(), nullable=True))
    op.add_column('stock_data_processed', sa.Column('target', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_data_processed', 'target')
    op.drop_column('stock_data_processed', 'rolling_std_200')
    # ### end Alembic commands ###
