apiVersion: v1
kind: Namespace
metadata:
  name: trading-bot-ingestion
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-ingestion-quota
  namespace: trading-bot-ingestion
spec:
  hard:
    cpu: "6"             # Increase CPU to match your total node capacity
    memory: "12Gi"       # Increase memory to match your node capacity
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: data-ingestion-limits
  namespace: trading-bot-ingestion
spec:
  limits:
  - default:
      cpu: "1"             # Increased from 0.7 to 1 CPU for containers
      memory: "1.5Gi"      # Increased from 1Gi to 1.5Gi
    defaultRequest:
      cpu: "0.7"           # Increased from 0.5 to 0.7 CPU
      memory: "1Gi"        # Increased from 512Mi to 1Gi
    type: Container
