apiVersion: v1
kind: Namespace
metadata:
  name: trading-bot-processing
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: data-processing-quota
  namespace: trading-bot-processing
spec:
  hard:
    cpu: "1.5"             # Allows flexibility across Kafka and PostgreSQL
    memory: "2Gi"          # Increased to 2Gi for better allocation to both services
    pods: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: data-processing-limits
  namespace: trading-bot-processing
spec:
  limits:
  - default:
      cpu: "0.7"           # Slightly increased to cover PostgreSQL needs
      memory: "1Gi"        # Set to 1Gi for PostgreSQL and Kafka container limits
    defaultRequest:
      cpu: "0.5"
      memory: "512Mi"      # Initial request still at 512Mi
    type: Container
