apiVersion: v1
kind: Namespace
metadata:
  name: trading-bot-inference
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: inference-quota
  namespace: trading-bot-inference
spec:
  hard:
    cpu: "1"
    memory: "1Gi"
    pods: "5"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: inference-limits
  namespace: trading-bot-inference
spec:
  limits:
  - default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "0.5"
      memory: "512Mi"
    type: Container
