apiVersion: v1
kind: Namespace
metadata:
  name: trading-bot-execution
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: execution-quota
  namespace: trading-bot-execution
spec:
  hard:
    cpu: "0.5"
    memory: "512Mi"
    pods: "3"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: execution-limits
  namespace: trading-bot-execution
spec:
  limits:
  - default:
      cpu: "0.5"
      memory: "512Mi"
    defaultRequest:
      cpu: "0.2"
      memory: "256Mi"
    type: Container
