apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: trading-bot-model-training
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
