apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: trading-bot-model-training
spec:
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: webui
      port: 9090
      targetPort: 9090
