apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: trading-bot-model-training
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        - "--console-address=:9090"
        env:
        - name: MINIO_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ENDPOINT
        - name: MINIO_ROOT_USER 
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_USER 
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: MINIO_ROOT_PASSWORD
        ports:
        - containerPort: 9000 # API
        - containerPort: 9090  # WebUI
        volumeMounts:
        - name: minio-storage
          mountPath: /data
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-pvc
