apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: trading-bot-ingestion
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
  type: ClusterIP  # ClusterIP allows internal cluster communication
