"""Initial schema

Revision ID: 47811fdab50c
Revises: 
Create Date: 2024-11-30 16:38:43.580128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47811fdab50c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_data_raw', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('stock_data_raw', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('stock_data_raw', 'size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stock_data_raw', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stock_data_raw', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('stock_data_raw', 'size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stock_data_raw', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('stock_data_raw', 'symbol',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###
